name: Patch Revanced
on:
  workflow_dispatch:
  workflow_call:
jobs:
  Revanced:
    name: Patch Revanced-${{ matrix.Revanced }}
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Revanced: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Patch apk
        run: bash src/build/Revanced-${{ matrix.Revanced }}.sh
        env:
          repository: ${{ github.repository }}
      - name: Releasing APK files
        uses: ./.github/actions/release
