name: Patch Revanced Extended Android 6 & 7
on:
  workflow_dispatch:
  workflow_call:
jobs:
  patch:
    name: Patch Revanced Extended for Android 6 & 7
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Patch apk
        run: bash src/build/Revanced-Extended-Android-6-7.sh
        env:
          repository: ${{ github.repository }}
      - name: Releasing APK files
        uses: ./.github/actions/release